name: Go

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["bubbles", "json", "log", "toml", "yaml"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - run: go get ${{ matrix.dir }}
      - run: go vet ${{ matrix.dir }}
      - run: go test ${{ matrix.dir }}
      - run: go test -race ${{ matrix.dir }}
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          working-directory: ${{ matrix.dir }}
