name: Go

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["./bubbles", "./json", "./log", "./toml", "./yaml"]
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - run: go vet ./...
      - run: go test ./...
      - run: go test -race ./...
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: latest
          install-go: false
          working-directory: ${{ matrix.dir }}
