name: Go

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      #- uses: golangci/golangci-lint-action@v4.0.0
      #  with:
      #    version: v1.54
      #    args: $(find . -depth 1 -type dir -not \( -name ".git" -or -name ".github" \))
      - run: find . -type d -depth 1 -not \( -name ".git" -or -name ".github" \) -exec go vet {} \;
      - run: find . -type d -depth 1 -not \( -name ".git" -or -name ".github" \) -exec go test {} \;
      - run: find . -type d -depth 1 -not \( -name ".git" -or -name ".github" \) -exec go test -race {} \;
